### ISSUE TITLE
Access to the "Input Shaping" settings during printing.

### ISSUE THREAD

**Issue by KAPTOHKA** [rommulaner/Anycubic_Vyper_LCD_CE_6.1d#7]
Hi.
Sugges adding the ```Input Shaping``` button to screen #79 ```Tune Other``` instead of ```RGB``` (it is still on the next screen #77 ```Misc. Settings```) to access the ```Input Shaping``` settings during printing or on pause... 
Let it be...
![79_E_adjust_other](https://github.com/rommulaner/Anycubic_Vyper_LCD_CE_6.2/assets/89792648/cbfc122f-463a-4bd8-a196-693ba22b36b3)

**Comment by rommulaner** [comment]
Hey!
Good point, but why should someone change the values during printing? You can't even see the changes on the calibration print properly or need to measure the ringing marks to calculate the frequencies. Is there any other printer that has this functionality?
Normally you do some test prints with varied frequencies and figure out the best values and that's it.

**Comment by KAPTOHKA** [comment]
Well, why do we need 2 identical ```RGB``` buttons located in one place?
It's better to have a ```IS``` button instead of one of the ```RGB``` buttons and we will get the only printer in the world with the ability to change IS on the fly during printing))), for example for tests... 
Let be...

**Comment by rommulaner** [comment]
The only thing is that the values are not applied directly after the change. Just switching to the page works as I tested it but at the moment you always have to go back to save the changes and it seems that they are applied immediately, but I'm not 100% sure. It also takes a moment to jump back, maybe because of the save operation.
Perhaps an apply button is needed and the code must be changed to save only after click on apply.
I must go ab deeper in that.

**Comment by rommulaner** [comment]
Implemented in 6.2.2. Currently Pre-Release.
